
- hosts: all
  tasks:
#  - name: create directory
#    file: 
#      path: /mnt/dvd
#      state: directory
#  become: 
#  vars:
#    - source_iso: "/run/media/root/RHEL-7.5\ Server.x86_64"
#    - dest_iso: "/run/media/root/RHEL-7.5\ Server.x86_64"
#    - repo_mount: "/mnt/dvd"
#  tasks:
#  - name: upload iso file
#    copy:
#     src: "{{source_iso}}" 
#     dest: "{{dest_iso}}"
#     force: no
#  - name: mount iso
#    mount:
#      path: "{{repo_mount}}" 
#      src: "{{dest_iso}}"
#      fstype: iso9660
#      opts: loop,ro
#      state: mounted
#  - name: Instll yum
#    yum_repository:
#      name: dvd1
#     description: rpm packages
#      file: yum
#      baseurl: "file://{{repo_mount}}"
#      enabled: yes
#      gpgcheck: no
  - name: Install apache packages 
    yum:
      name: httpd
      state: present
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started
  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
  - name: Copy Java rpm file to server
    copy:
     src: /root/Desktop/ansible/jdk-8u171-linux-x64.rpm  
     dest: /root/Desktop/jdk-8u171-linux-x64.rpm 
  - name: Install java package.
    yum: 
     name : /root/Desktop/jdk-8u171-linux-x64.rpm
     state: present
  - name: Set path for java file
    lineinfile:
      dest: /etc/environment
      state: present
      regexp: 'JAVA_HOME'
      line: 'JAVA_HOME: /usr/java/jdk1.8.0_171-amd64/'
      dest: /etc/environment
      state: present
      regexp: 'PATH'
      line: 'PATH=/usr/java/jdk1.8.0_171-amd64/bin:$PATH'
  - name: Copy Hadoop rpm file to server
    copy:
     src: /root/Desktop/ansible/hadoop-1.2.1-1.x86_64.rpm 
     dest: /root/Desktop/hadoop-1.2.1-1.x86_64.rpm 
  - name: Install hadoop package.
    command: rpm -ivh /root/Desktop/hadoop-1.2.1-1.x86_64.rpm --force 
  - name: Copy python rpm file to location
    copy:
     src: /root/Desktop/ansible/python36-3.6.3-7.el7.x86_64.rpm 
     dest: /root/Desktop/python36-3.6.3-7.el7.x86_64.rpm 
  - name: Copy Another python file
    copy:
     src:  /root/Desktop/rhel7_5_rpm_extras/python36-devel-3.6.3-7.el7.x86_64.rpm
     dest: /root/Desktop/python36-devel-3.6.3-7.el7.x86_64.rpm
#  - name: Install Python36
#   command: rpm -ivh /root/Desktop/python36-devel-3.6.3-7.el7.x86_64.rpm
#   command: rpm -ivh /root/Desktop/python36-3.6.3-7.el7.x86_64.rpm
#  - name: Install python
#    sudo: yes   
#    roles:
#      - role: python-from-source
#        pyfsrc_version: 3.4.3 
   
